import '@/scss/style.scss'

// Components
import SupHeader from "@/components/supHeader/SupHeader";
import SubHeader from '@/components/subHeader/SubHeader';
import Footer from "@/components/footer/Footer";

export const metadata = {
  title: "Welcome E-Comm",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <SupHeader/>
        <SubHeader/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
